### PR TITLE
create the guest account as an inactive account

### PR DESCRIPTION
**Pull request by drj11**

### CODE REVIEW

**Comment by drj11** [comment]
@ilya I've tested this in my vagrant build, but would appreciate someone else trying it in vagrant before merging.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;moRhXHHz&#x2F;245-test-create-the-guest-account-as-an-inactive-account-pr"> test &quot;create the guest account as an inactive account&quot; PR</a>

**Comment by scottx611x** [comment]
@drj11 Just tried this out with an existing vm and a new one. The guest user is created and `active` both times.

**Comment by hackdna** [comment]
Tested 401e979. Vagrant provisioning worked in both existing and brand new VMs. Deployment to AWS failed. See #932 for details.

**Pull request merged**
