### PR TITLE
Bump librarian-puppet version

### PR DESCRIPTION
**Pull request by drj11**
This fixes https://github.com/parklab/refinery-platform/issues/1220

### CODE REVIEW

**Comment by drj11** [comment]
Merge at will @hackdna

**Comment by drj11** [comment]
Just realised that this potentially affects clean Vagrant builds; but I haven't had time to check.

**Comment by hackdna** [comment]
Thanks. Why would this affect clean Vagrant deployments? Could you verify this? We might have new folks trying to deploy Refinery.

**Comment by drj11** [comment]
The `Vagrantfile` uses `bootstrap.sh`; trying in Vagrant now.

**Comment by scottx611x** [comment]
@drj11 Just tried bringing up a fresh VM and I'm seeing this error:
```
==> default: ERROR:  Error installing librarian-puppet:
==> default: 	activesupport requires Ruby version >= 2.2.2.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by drj11** [comment]
@scottx611x this branch isn't merged yet! (which branch are you using?)

**Comment by scottx611x** [comment]
@drj11 Oh boy! oops I'm gonna get some coffee and try this out once more :)

**Comment by scottx611x** [comment]
@drj11 This works fine on a fresh VM (after actually checking out your branch!!!!!)

**Comment by drj11** [comment]
@scottx611x works for me too. Merging.

**Pull request merged**
