### PR TITLE
Django superuser (admin) has configurable password

### PR DESCRIPTION
**Pull request by drj11**
You can now configure the password for the Django admin user. Fixes the second half of #932.

### CODE REVIEW

**Comment by drj11** [comment]
Before merging:

[ ] fix travis build (by rebasing?)
[ ] wiki documentation

**Comment by drj11** [comment]
- [ ] before merging change cp command to use puppet File resource type

**Comment by scottx611x** [comment]
@drj11 You can go ahead and merge this if you'd like. I was having issues successfully running analyses on my `django_1.7_upgrade` branch. I can address the `syncdb` instances within my branch as well. I think it'll be just as easy that way.

**Comment by scottx611x** [comment]
Related to : https://github.com/parklab/refinery-platform/issues/1008

**Pull request merged**
