### PR TITLE
Scottx611x/galaxy large file uploads

### PR DESCRIPTION
**Pull request by scottx611x**
This includes the appropriate fixes to what I've accidentally reverted and introduced back into `develop`.

If @drj11, @flekschas, @jmarx, and @hackdna would please doubled check this to make sure your changes have properly persisted after this mess that would be great! Sorry for the mixup!

### CODE REVIEW

**Comment by jkmarx** [comment]
@scottx611x: My changes look okay.

**Comment by hackdna** [comment]
Could you provide the commit where you reverted?

**Comment by scottx611x** [comment]
@hackdna https://github.com/parklab/refinery-platform/commit/d71f5a1b7c882a5e3db62dd5fcd3574335e734ba

**Comment by hackdna** [comment]
Thanks. Could you perform end-to-end testing before we merge this (import an ISA-archive and a tabular file then run analyses on those data sets)?

**Comment by scottx611x** [comment]
@hackdna most definitely!

**Comment by scottx611x** [comment]
End to end testing is done and working fine. I can test on AWS as well before closing if thats preferred?

**Pull request merged**
