### PR TITLE
Connect to pre-existing RDS

### PR DESCRIPTION
**Pull request by drj11**
This changes the AWS deployment so that the instance that is created connects to a pre-existing, and therefore persistent, RDS.

### CODE REVIEW

**Comment by drj11** [comment]
Not ready to merge yet. Travis fails (because pep8).

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;uM9OFk77&#x2F;207-merge-david-s-pull-request"> Merge David&#39;s pull request</a>

**Comment by hackdna** [comment]
I've merged this pull request even though I've encountered a few issues with this implementation:
* key pair name is hardcoded to "id_rsa" (should be able to specify on the command line)
* it is not clear what exact RDS role permission to assign when creating the RDS instance manually
* it is also not clear what to use for RDS instance class, db engine version, amount of storage, VPC security group/publicly accessible and database name
* instance profile is not created by default when creating a role via web UI; I had to do:
 * `aws iam create-instance-profile --instance-profile-name refinery-web`
 * `aws iam add-role-to-instance-profile --instance-profile-name refinery-web --role-name refinery-web`
* most importantly, for some reason Refinery was not actually provisioned on the EC2 instance (I've tried creating the stack twice but it could be an error with my setup)

**Comment by drj11** [comment]
@hackdna I should've put a clearer hold on the PR. I haven't checked the vagrant provision yet, and overnight I convinced myself it was probably broken (probably a simple typo).

**Comment by drj11** [comment]
@hackdna FWIW the problem is probably that you assigned the RDS to a role. There are so many things to go wrong.

I've created #859 (ssh keys) and #860 (rds)

**Comment by hackdna** [comment]
Sorry, I meant "RDS role" instead of "RDS instance". I've corrected the comment above.

**Comment by drj11** [comment]
okay, cool. We must have found different ways to create the IAM Role. I am pretty sure I didn't have to create the instance role separately. Ah wait, I used the Web UI to create the IAM role; did you use the CLI tools?

**Comment by hackdna** [comment]
I've created the RDS role via the web UI and then I created the instance profile and added the RDS role to it via the CLI (see [above](https://github.com/parklab/refinery-platform/pull/858#issuecomment-175982585)).

**Pull request merged**
